rules: []
rulesConfigs: []
pages: []
resourceServers: []
clients:
  - name: Auth0 Migration Client
    app_type: non_interactive
    cross_origin_authentication: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
databases: []
connections: []
tenant:
  friendly_name: Tindahan Natin
  support_email: support@aebibtech.com
emailProvider: {}
emailTemplates: []
clientGrants: []
guardianFactors: []
guardianPolicies:
  policies: []
guardianPhoneFactorMessageTypes:
  message_types: []
roles: []
branding:
  templates: []
phoneProviders: []
phoneTemplates: []
prompts:
  customText: {}
  partials: {}
actions: []
triggers: {}
organizations: []
attackProtection:
  botDetection:
    challenge_password_policy: never
    challenge_passwordless_policy: never
    challenge_password_reset_policy: never
    allowlist: []
    bot_detection_level: medium
    monitoring_mode_enabled: false
  breachedPasswordDetection:
    enabled: false
    shields: []
    admin_notification_frequency: []
    method: standard
  bruteForceProtection:
    enabled: true
    shields:
      - block
      - user_notification
    mode: count_per_identifier_and_ip
    allowlist: []
    max_attempts: 10
  suspiciousIpThrottling:
    enabled: true
    shields:
      - admin_notification
      - block
    allowlist: []
riskAssessment:
  new_device:
    remember_for: 30
  settings:
    enabled: false
logStreams: []
customDomains: []
themes: []
forms: []
flows: []
flowVaultConnections: []
selfServiceProfiles: []
userAttributeProfiles: []
connectionProfiles: []
tokenExchangeProfiles: []
